Repository KinsonDigital/Infrastructure, pull requests merged in 2024-01, with the labels that each got.

#206 🚧Update kd_clients library for bug fix
  .github/workflows/workflow-version-status-check.yml
  deno.lock
  deps.ts
Labels: 🐛bug, 📦dependency update

#209 🚀Production Release (v13.6.1)
  .github/release-templates/prev-pr-release-template.md
  .github/release-templates/prod-pr-release-template.md
  .github/workflows/add-new-item-to-project.yml
  .github/workflows/build-csharp-project.yml
  .github/workflows/build-status-check.yml
  .github/workflows/dotnet-action-release.yml
  .github/workflows/dotnet-lib-release.yml
  .github/workflows/internal-prepare-release.yml
  .github/workflows/run-csharp-tests.yml
  .github/workflows/sync-pr-to-issue.yml
  ReleaseNotes/ProductionReleases/Release-Notes-v13.6.1.md
  deno.json
Labels: 🚀Production Release

#211 🚧Fix bug with scripts
  .github/ISSUE_TEMPLATE/project-item-issue-template.yml
  .vscode/settings.json
  cicd/scripts/github-release-does-not-exist.ts
  cicd/scripts/milestone-exists.ts
Labels: 🐛bug

#215 🚧Fix issue with building tweet
  cicd/core/ReleaseTweetBuilder.ts
Labels: 🐛bug, high priority

#219 🚧Add repo variable trimming
  .github/workflows/resolve-csharp-proj-file.yml
Labels: high priority, tech debt, ♻️cicd
